// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIbaD5iu_IgWJKBY1xDln-A_wjPfr2K3s',
    appId: '1:280241494674:web:f177febe7fe74b6ef2a44b',
    messagingSenderId: '280241494674',
    projectId: 'project7-e7c95',
    authDomain: 'project7-e7c95.firebaseapp.com',
    databaseURL: 'https://project7-e7c95-default-rtdb.firebaseio.com',
    storageBucket: 'project7-e7c95.firebasestorage.app',
    measurementId: 'G-4JW4H9QVDG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaH8D50cqp-4EwZMRHT7xS6x0E7TQSNT8',
    appId: '1:280241494674:android:e481f705510bf7acf2a44b',
    messagingSenderId: '280241494674',
    projectId: 'project7-e7c95',
    databaseURL: 'https://project7-e7c95-default-rtdb.firebaseio.com',
    storageBucket: 'project7-e7c95.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCA6S3xwWakGxLQa25n55bILbQpQ2kuiKw',
    appId: '1:280241494674:ios:edb40affb6e5cabff2a44b',
    messagingSenderId: '280241494674',
    projectId: 'project7-e7c95',
    databaseURL: 'https://project7-e7c95-default-rtdb.firebaseio.com',
    storageBucket: 'project7-e7c95.firebasestorage.app',
    iosBundleId: 'com.example.appWallpaper',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCA6S3xwWakGxLQa25n55bILbQpQ2kuiKw',
    appId: '1:280241494674:ios:edb40affb6e5cabff2a44b',
    messagingSenderId: '280241494674',
    projectId: 'project7-e7c95',
    databaseURL: 'https://project7-e7c95-default-rtdb.firebaseio.com',
    storageBucket: 'project7-e7c95.firebasestorage.app',
    iosBundleId: 'com.example.appWallpaper',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIbaD5iu_IgWJKBY1xDln-A_wjPfr2K3s',
    appId: '1:280241494674:web:b07809241536c39df2a44b',
    messagingSenderId: '280241494674',
    projectId: 'project7-e7c95',
    authDomain: 'project7-e7c95.firebaseapp.com',
    databaseURL: 'https://project7-e7c95-default-rtdb.firebaseio.com',
    storageBucket: 'project7-e7c95.firebasestorage.app',
    measurementId: 'G-2FEHL9BJDS',
  );

}