// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPy6AQWNpBdMBXJRi8T4mlO0hFuhTMm3k',
    appId: '1:855235878644:web:6bc90f38e2e0ae159908a1',
    messagingSenderId: '855235878644',
    projectId: 'appwallpaper-1dceb',
    authDomain: 'appwallpaper-1dceb.firebaseapp.com',
    storageBucket: 'appwallpaper-1dceb.firebasestorage.app',
    measurementId: 'G-VDSDHT3MFM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDP4uj9gwQko94vmdTBhWi-ikGTU-21zcY',
    appId: '1:855235878644:android:355b4722337970839908a1',
    messagingSenderId: '855235878644',
    projectId: 'appwallpaper-1dceb',
    storageBucket: 'appwallpaper-1dceb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALIaQj-yOLBC7aWTftWg_gvR9ssOrEaho',
    appId: '1:855235878644:ios:d960ba420bf0bcf29908a1',
    messagingSenderId: '855235878644',
    projectId: 'appwallpaper-1dceb',
    storageBucket: 'appwallpaper-1dceb.firebasestorage.app',
    iosBundleId: 'com.example.appWallpaper',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALIaQj-yOLBC7aWTftWg_gvR9ssOrEaho',
    appId: '1:855235878644:ios:d960ba420bf0bcf29908a1',
    messagingSenderId: '855235878644',
    projectId: 'appwallpaper-1dceb',
    storageBucket: 'appwallpaper-1dceb.firebasestorage.app',
    iosBundleId: 'com.example.appWallpaper',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPy6AQWNpBdMBXJRi8T4mlO0hFuhTMm3k',
    appId: '1:855235878644:web:c17f26c75948fa7f9908a1',
    messagingSenderId: '855235878644',
    projectId: 'appwallpaper-1dceb',
    authDomain: 'appwallpaper-1dceb.firebaseapp.com',
    storageBucket: 'appwallpaper-1dceb.firebasestorage.app',
    measurementId: 'G-R9TS6GLSEK',
  );
}
