name: app_wallpaper
description: "A wallpaper app with various features."

version: 1.0.0+1

environment:
  sdk: '>=3.8.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  
  provider: ^6.1.1
  
  # UI components
  cached_network_image: ^3.3.1
  flutter_staggered_grid_view: ^0.7.0
  shimmer: ^3.0.0
  lottie: ^2.7.0
  
  # Authentication
  shared_preferences: ^2.2.2
  
  # Navigation
  go_router: ^12.1.3
  
  # Image handling
  image_picker: ^1.0.4
  image_gallery_saver: ^2.0.3
  path_provider: ^2.1.1
  
  # Animation
  flutter_animate: ^4.2.0
  
  # UI utilities
  flutter_svg: ^2.0.9
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/animations/
  

